# Performance data receiver

version: "1.0"
services:
  collector:
    user: root
    extra_hosts:
      - "MQTT:192.168.1.50"
      - "LOGSTASH:192.168.1.51"
    ports:
      - target: 5044
        published: 5044
        protocol: tcp
        mode: host
    networks:
      default:
      outside:
        ipv4_address:
          192.168.1.51
    environment:
      - ELASTIC_CONTAINER=false
    build:
      context: ./logstash
      dockerfile: Dockerfile
    depends_on:
      queue:
        condition: service_started
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/mqtt.conf:/usr/share/logstash/pipeline/mqtt.conf
      - ./output/:/usr/share/logstash/output

  queue:
    image: "project-faster/mosquitto"
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    extra_hosts:
      - "MQTT:192.168.1.50"
      - "LOGSTASH:192.168.1.51"
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
    networks:
      default:
      outside:
        ipv4_address:
          192.168.1.50
    volumes:
      - ./mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf

  server:
    image: "project-faster/qpep_linux"
    depends_on:
      - queue
      - collector
    ports:
      - target: 1445
        published: 1445
        protocol: udp
        mode: host
    volumes:
      - ./server:/build/config
    entrypoint:
      - sh -c 'cd /build && ./qpep -server'


networks:
  outside:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
